name = "git"
followups = ["Remember to set the ssh key for signing commits."]


[packages]
apt = ["git", "vim"]
pacman = ["git", "vim"]


[[dirs]]
path = "~/.ssh"
mode = "700"

[[dirs]]
path = "~/.config/moi/git"
mode = "755"

[[files]]
src = "files/config"
dst = "~/.config/moi/git/config"
mode = "644"

[[commands]]
run = """
git config --global --add include.path "$HOME/.config/moi/git/config"
"""
unless = """
git config --global --get-all include.path 2>/dev/null | grep -Fx "$HOME/.config/moi/git/config"
"""
requires = ["git", "grep"]
