name = "core"


[packages]
apt = [
    "build-essential",
    "ca-certificates",
    "curl",
    "pkg-config",
    "unzip",
]
pacman = [
    "base-devel",
    "ca-certificates",
    "curl",
    "pkgconf",
    "unzip",
]
