name = "devcontainer"
depends_on = ["node", "docker"]


[[commands]]
run = "npm install -g @devcontainers/cli"
unless = "command -v devcontainer"
requires = ["npm"]


[[files]]
src = "files/exec_devcontainer.sh"
dst = "~/.local/bin/exec_devcontainer"
mode = "755"
