local c = require "colors.solarized_dark.palette"

local M = {}

local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

function M.apply()
  hi("Normal", { fg = c.base0, bg = "NONE" })
  hi("NormalNC", { fg = c.base0, bg = "NONE" })
  hi("NormalFloat", { fg = c.base0, bg = "NONE" })
  hi("FloatBorder", { fg = c.cyan, bg = "NONE" })
  hi("FloatTitle", { fg = c.cyan, bg = "NONE" })
  hi("SignColumn", { bg = "NONE" })
  hi("FoldColumn", { fg = c.base01, bg = "NONE" })
  hi("EndOfBuffer", { fg = c.base03, bg = "NONE" })

  hi("ColorColumn", { bg = c.base02 })
  hi("Cursor", { fg = c.base03, bg = c.cursor })
  hi("CursorLine", { bg = c.base02 })
  hi("CursorLineNr", { fg = "#949494", bg = "NONE" })
  hi("LineNr", { fg = c.base01, bg = "NONE" })
  hi("MatchParen", { fg = c.cyan, bg = c.base02, bold = true })
  hi("NonText", { fg = c.base01, bg = "NONE" })
  hi("Pmenu", { fg = c.base1, bg = c.ui_panel })
  hi("PmenuSel", { fg = c.base2, bg = c.ui_select })
  hi("PmenuSbar", { bg = c.ui_panel })
  hi("PmenuThumb", { bg = c.base01 })
  hi("Search", { fg = c.base03, bg = c.yellow })
  hi("IncSearch", { fg = c.base03, bg = c.orange })
  hi("Substitute", { fg = c.base03, bg = c.cyan })
  hi("StatusLine", { fg = c.base1, bg = c.ui_panel })
  hi("StatusLineNC", { fg = c.base01, bg = c.ui_panel })
  hi("TabLine", { fg = c.base1, bg = c.ui_hover_light })
  hi("TabLineFill", { bg = "NONE" })
  hi("TabLineSel", { fg = c.base2, bg = "NONE" })
  hi("VertSplit", { fg = c.ui_panel, bg = "NONE" })
  hi("Visual", { bg = c.selection })
  hi("Whitespace", { fg = c.base1 })
  hi("WinSeparator", { fg = c.ui_panel, bg = "NONE" })

  hi("Comment", { fg = c.base01, italic = true })
  hi("Constant", { fg = c.yellow })
  hi("String", { fg = c.cyan })
  hi("Character", { fg = c.orange })
  hi("Number", { fg = c.magenta })
  hi("Boolean", { fg = c.yellow })
  hi("Float", { fg = c.magenta })
  hi("Identifier", { fg = c.blue })
  hi("Function", { fg = c.blue })
  hi("Statement", { fg = c.green })
  hi("Conditional", { fg = c.green })
  hi("Repeat", { fg = c.green })
  hi("Label", { fg = c.green })
  hi("Operator", { fg = c.base0 })
  hi("Keyword", { fg = c.green })
  hi("Exception", { fg = c.green })
  hi("PreProc", { fg = c.yellow })
  hi("Include", { fg = c.blue })
  hi("Define", { fg = c.yellow })
  hi("Macro", { fg = c.yellow })
  hi("PreCondit", { fg = c.yellow })
  hi("Type", { fg = c.orange })
  hi("StorageClass", { fg = c.base1, bold = true })
  hi("Structure", { fg = c.orange })
  hi("Typedef", { fg = c.orange })
  hi("Special", { fg = c.orange })
  hi("SpecialChar", { fg = c.orange })
  hi("Tag", { fg = c.blue })
  hi("Delimiter", { fg = c.base0 })
  hi("SpecialComment", { fg = c.base01, italic = true })
  hi("Debug", { fg = c.red })
  hi("Underlined", { fg = c.violet, underline = true })
  hi("Ignore", { fg = c.base01 })
  hi("Error", { fg = c.red })
  hi("Todo", { fg = c.magenta, bold = true })

  hi("DiffAdd", { fg = c.green, bg = "NONE" })
  hi("DiffChange", { fg = c.orange, bg = "NONE" })
  hi("DiffDelete", { fg = c.red, bg = "NONE" })
  hi("DiffText", { fg = c.blue, bg = "NONE" })

  hi("DiagnosticError", { fg = c.red })
  hi("DiagnosticWarn", { fg = c.yellow })
  hi("DiagnosticInfo", { fg = c.blue })
  hi("DiagnosticHint", { fg = c.cyan })
  hi("DiagnosticOk", { fg = c.green })
  hi("DiagnosticVirtualTextError", { fg = c.red, bg = "NONE" })
  hi("DiagnosticVirtualTextWarn", { fg = c.yellow, bg = "NONE" })
  hi("DiagnosticVirtualTextInfo", { fg = c.blue, bg = "NONE" })
  hi("DiagnosticVirtualTextHint", { fg = c.cyan, bg = "NONE" })
  hi("DiagnosticUnderlineError", { sp = c.red, undercurl = true })
  hi("DiagnosticUnderlineWarn", { sp = c.yellow, undercurl = true })
  hi("DiagnosticUnderlineInfo", { sp = c.blue, undercurl = true })
  hi("DiagnosticUnderlineHint", { sp = c.cyan, undercurl = true })

  hi("GitSignsAdd", { fg = c.green, bg = "NONE" })
  hi("GitSignsChange", { fg = c.orange, bg = "NONE" })
  hi("GitSignsDelete", { fg = c.red, bg = "NONE" })

  hi("RainbowDelimiterRed", { fg = c.bracket1 })
  hi("RainbowDelimiterYellow", { fg = c.yellow })
  hi("RainbowDelimiterBlue", { fg = c.magenta })
  hi("RainbowDelimiterOrange", { fg = c.bracket1 })
  hi("RainbowDelimiterGreen", { fg = c.yellow })
  hi("RainbowDelimiterViolet", { fg = c.magenta })
  hi("RainbowDelimiterCyan", { fg = c.bracket1 })

  hi("@comment", { link = "Comment" })
  hi("@string", { link = "String" })
  hi("@string.regexp", { fg = c.red })
  hi("@number", { link = "Number" })
  hi("@boolean", { link = "Boolean" })
  hi("@constant", { fg = c.orange })
  hi("@constant.builtin", { fg = c.yellow })
  hi("@constant.macro", { fg = c.yellow })
  hi("@variable", { fg = c.blue })
  hi("@variable.builtin", { fg = c.blue })
  hi("@variable.parameter", { fg = c.base0 })
  hi("@function", { link = "Function" })
  hi("@function.call", { link = "Function" })
  hi("@function.builtin", { fg = c.blue })
  hi("@constructor", { fg = c.orange })
  hi("@keyword", { link = "Keyword" })
  hi("@keyword.function", { fg = c.green })
  hi("@keyword.operator", { fg = c.green })
  hi("@keyword.import", { fg = c.blue })
  hi("@type", { fg = c.orange })
  hi("@type.builtin", { fg = c.green })
  hi("@type.definition", { fg = c.orange })
  hi("@module", { fg = c.orange })
  hi("@property", { fg = c.base1 })
  hi("@tag", { fg = c.blue })
  hi("@tag.attribute", { fg = c.base1 })
  hi("@tag.delimiter", { fg = c.base01 })
  hi("@punctuation", { fg = c.base0 })
  hi("@punctuation.bracket", { fg = c.base0 })
  hi("@punctuation.delimiter", { fg = c.base0 })
  hi("@operator", { link = "Operator" })
  hi("@markup.heading", { fg = c.blue, bold = true })
  hi("@markup.raw", { fg = c.cyan })
  hi("@markup.list", { fg = c.yellow })
  hi("@markup.quote", { fg = c.green })
  hi("@markup.strong", { fg = c.magenta, bold = true })
  hi("@markup.italic", { fg = c.magenta, italic = true })
  hi("@diff.plus", { fg = c.green })
  hi("@diff.minus", { fg = c.red })
  hi("@diff.delta", { fg = c.orange })
end

return M
