name = "docker"
notes = [
    "Run `sudo usermod -aG docker $USER` to add your user to the docker group.",
]


[packages]
pacman = ["docker"]


[[commands]]
platform = "debian"
run = """
curl -fsSL https://get.docker.com | bash
"""
unless = "command -v docker"
requires = ["bash", "curl"]
