name = "docker"
depends_on = ["zsh"]
notes = [
    "Run `sudo usermod -aG docker $USER` to add your user to the docker group.",
]


[[commands]]
run = """
curl -fsSL https://get.docker.com | bash
"""
unless = "command -v docker"
requires = ["bash", "curl"]
