name = "keychain"
depends_on = ["zsh"]
notes = ["Add SSH keys to keychain manually as needed."]


[packages]
apt = ["keychain"]


[[blocks]]
src = "files/keychain.sh"
dst = "~/.zshrc"
marker = "cfg:keychain"


[[blocks]]
src = "files/keychain.sh"
dst = "~/.bashrc"
marker = "cfg:keychain"
