name = "cargo"
depends_on = ["zsh", "bash"]


[[blocks]]
src = "files/cargo.sh"
dst = "~/.zshrc"
marker = "moi:cargo"

[[blocks]]
src = "files/cargo.sh"
dst = "~/.bashrc"
marker = "moi:cargo"


[[commands]]
# ref: https://rust-lang.org/tools/install
# ref: https://github.com/rust-lang-deprecated/rustup.sh/issues/83
run = """
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
"""
unless = "command -v cargo"
requires = ["curl"]


[env]
path_prepend = ["~/.cargo/bin"]
