name = "git"
depends_on = ["core"]
notes = ["Remember to set the ssh key for signing commits."]


[packages]
apt = ["git"]


[[dirs]]
path = "~/.ssh"
mode = "700"


[[files]]
src = "files/.gitconfig"
dst = "~/.gitconfig"
mode = "644"
