name = "core"


[packages]
apt = [
    "btop",
    "build-essential",
    "ca-certificates",
    "curl",
    "ffmpeg",
    "git",
    "gnupg",
    "libssl-dev",
    "lsb-release",
    "net-tools",
    "pkg-config",
    "unzip",
    "wget",
]
